### ISSUE TITLE
Versioneer not working as intented

### ISSUE THREAD

**Issue by hmacdope** [choderalab/mtenn#8]
Versioneer is not picking up the right tags as it doesn't have the right setup in `pyroject.toml`

```toml
[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "src/myproject/_version.py"
versionfile_build = "myproject/_version.py"
tag_prefix = ""
parentdir_prefix = "myproject-"
```
